{"uuid": "51eedf39-a7c4-436a-9faf-18a00f2f9a7b", "children": ["dc06fccd-bf9b-468c-a93a-4f4b0ad5b2d5", "5c7dac98-d47e-431a-a723-1b4925f09580"], "befores": [{"name": "test_setup", "status": "passed", "start": 1584699514959, "stop": 1584699522422}], "afters": [{"name": "test_setup::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: Tried to run command without establishing a connection\n\n", "trace": "  File \"C:\\Users\\veeresh.m\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\allure_commons\\_allure.py\", line 185, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Users\\veeresh.m\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 796, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\veeresh.m\\PycharmProjects\\SALNG_Core\\conftest.py\", line 18, in test_setup\n    driver.close()\n  File \"C:\\Users\\veeresh.m\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 688, in close\n    self.execute(Command.CLOSE)\n  File \"C:\\Users\\veeresh.m\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\veeresh.m\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1586149676200, "stop": 1586149676218}], "start": 1584699514959, "stop": 1586149676218}